package com.mycompany.da1.view.components;

import com.mycompany.da1.view.events.EventMenuSelected;
import com.mycompany.da1.view.model.ModelMenu;
import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionAdapter;
import javax.swing.JFrame;

/**
 *
 * @author asus
 */
public class JPanelMenu extends javax.swing.JPanel {

    public EventMenuSelected event;
    public void addEventMenuSelected(EventMenuSelected event){
        this.event = event;
        listMenu.addEventMenuSelected(event);
    }

    
    public JPanelMenu() {
        initComponents();
        setOpaque(false);
        listMenu.setOpaque(false);
        init();
    }

    private void init(){
 listMenu.addItems(new ModelMenu("house","Trang Chủ",ModelMenu.MenuType.MENU));
        listMenu.addItems(new ModelMenu("","",ModelMenu.MenuType.SPACE));
        listMenu.addItems(new ModelMenu("cart","Bán Hàng",ModelMenu.MenuType.MENU));
        listMenu.addItems(new ModelMenu("","",ModelMenu.MenuType.SPACE));
        listMenu.addItems(new ModelMenu("product","Sản Phẩm",ModelMenu.MenuType.MENU));
        listMenu.addItems(new ModelMenu("","",ModelMenu.MenuType.SPACE));
        listMenu.addItems(new ModelMenu("employee","Nhân Viên",ModelMenu.MenuType.MENU));
        listMenu.addItems(new ModelMenu("","",ModelMenu.MenuType.SPACE));
        listMenu.addItems(new ModelMenu("traveler","Khách Hàng",ModelMenu.MenuType.MENU));
        listMenu.addItems(new ModelMenu("","",ModelMenu.MenuType.SPACE));
        listMenu.addItems(new ModelMenu("bill","Hóa Đơn",ModelMenu.MenuType.MENU));
        listMenu.addItems(new ModelMenu("","",ModelMenu.MenuType.SPACE));
        listMenu.addItems(new ModelMenu("analytics","Thống Kê",ModelMenu.MenuType.MENU));
        listMenu.addItems(new ModelMenu("","",ModelMenu.MenuType.SPACE));
        listMenu.addItems(new ModelMenu("analytics","Khuyến Mại",ModelMenu.MenuType.MENU));
        
        listMenu.addItems(new ModelMenu("","",ModelMenu.MenuType.SPACE));
        listMenu.addItems(new ModelMenu("check-out","Đăng Xuất",ModelMenu.MenuType.MENU));
    }
   
    
    @Override
    protected void paintChildren(Graphics g) {
         Graphics2D g2 = (Graphics2D) g;
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        GradientPaint g1 = new GradientPaint(0, 0, Color.decode("#FFFF99"), 0, getHeight(), Color.decode("#FFA500"));
        g2.setPaint(g1);
        g2.fillRoundRect(0, 0, getWidth(), getHeight(), 15, 15);
        g2.fillRect(getWidth() - 20, 0, getWidth(), getHeight());
        super.paintChildren(g); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
    }
    
    private  int x;
    private  int y;
    
    public  void initMoving(JFrame jFrame){
        jPanel_logo.addMouseListener(new MouseAdapter(){
            @Override
            public void mousePressed(MouseEvent e) {
                   x = e.getX();
                   y = e.getY();
            }
            
        });
        jPanel_logo.addMouseMotionListener(new MouseMotionAdapter(){
            @Override
            public void mouseDragged(MouseEvent e) {
                jFrame.setLocation(e.getXOnScreen() - x, e.getYOnScreen() - y);
            }
            
        });
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_logo = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        listMenu = new com.mycompany.da1.view.swing.ListMenu<>();

        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(215, 454));

        jPanel_logo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel_logo.setOpaque(false);

        jLabel2.setBackground(new java.awt.Color(255, 102, 0));
        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("SHOES");

        javax.swing.GroupLayout jPanel_logoLayout = new javax.swing.GroupLayout(jPanel_logo);
        jPanel_logo.setLayout(jPanel_logoLayout);
        jPanel_logoLayout.setHorizontalGroup(
            jPanel_logoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
        );
        jPanel_logoLayout.setVerticalGroup(
            jPanel_logoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_logoLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(listMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel_logo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(listMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel_logo;
    private com.mycompany.da1.view.swing.ListMenu<String> listMenu;
    // End of variables declaration//GEN-END:variables
}
