/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.da1.view.components;

import com.mycompany.da1.view.model.ModelMenu;

import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;

/**
 *
 * @author asus
 */
public class JPanelMenuItem extends javax.swing.JPanel {

    private boolean selected;
    private boolean over;

    /**
     * Creates new form Menu_Items
     * @param data
     */
    public JPanelMenuItem(ModelMenu data) {
        initComponents();
        setOpaque(false);
        if (data.getMenuType()== ModelMenu.MenuType.MENU) {
          jlb_icon.setIcon(data.toIcon());
            jlb_menuName.setText(data.getName());
        } else if (data.getMenuType() == ModelMenu.MenuType.TITLE) {
            jlb_icon.setText(data.getName());
            jlb_menuName.setFont(new Font("sansserif", 1, 12) {
            });
        } else {
            jlb_menuName.setText(" ");
        }

    }

    public void setSelected(boolean selected) {
        this.selected = selected;
        repaint();
    }
    public void setOver(boolean  over){
        this.over = over;
        repaint();
    }

    @Override
    protected void paintComponent(Graphics g) {
        if (selected || over) {
            Graphics2D g2 = (Graphics2D) g;
            g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
            if (selected) {
                g2.setColor(new Color(255, 255, 255, 80));
            } else {
                g2.setColor(new Color(255, 255, 255, 20));
            }
            g2.fillRoundRect(10, 0, getWidth() - 20, getHeight(), 5, 5);
        }
        super.paintComponent(g);
        
    }
        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlb_icon = new javax.swing.JLabel();
        jlb_menuName = new javax.swing.JLabel();
        jlb_space2 = new javax.swing.JLabel();
        jlb_space1 = new javax.swing.JLabel();

        jlb_menuName.setText("Menu Name");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jlb_icon)
                .addGap(10, 10, 10)
                .addComponent(jlb_space1)
                .addGap(18, 18, 18)
                .addComponent(jlb_menuName, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jlb_space2)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlb_icon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jlb_space2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jlb_space1))
            .addComponent(jlb_menuName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jlb_icon;
    private javax.swing.JLabel jlb_menuName;
    private javax.swing.JLabel jlb_space1;
    private javax.swing.JLabel jlb_space2;
    // End of variables declaration//GEN-END:variables

}
