/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.da1.view.form.sales;

import com.mycompany.da1.combobox.KhachHangCBB;
import com.mycompany.da1.combobox.TaiKhoanCBB;
import com.mycompany.da1.combobox.VoucherCBB;
import com.mycompany.da1.entity.HoaDonEntity;
import com.mycompany.da1.entity.KhachHangEntity;
import com.mycompany.da1.entity.TaiKhoanEntity;
import com.mycompany.da1.entity.VoucherEntity;
import com.mycompany.da1.service.IMPL.HoaDonIMPL;
import com.mycompany.da1.service.IMPL.KhachHangIMPL;
import com.mycompany.da1.service.IMPL.TaiKhoanIMPL;
import com.mycompany.da1.service.IMPL.VoucherServiceIMPL;
import com.mycompany.da1.view.JFrameMain;
import com.mycompany.da1.view.ToanCucStatic;
import com.mycompany.da1.view.events.EventDialogListener;

import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Quang
 */
public class InsertHoaDon extends javax.swing.JFrame  implements EventDialogListener {

    VoucherServiceIMPL voucher = new VoucherServiceIMPL();
    KhachHangIMPL khachHangIMPL = new KhachHangIMPL();
    TaiKhoanIMPL taiKhoanIMPL = new TaiKhoanIMPL();
    HoaDonIMPL hoaDonIMPL = new HoaDonIMPL();
    private EventDialogListener dialogListener;

    /**
     * Creates new form InsertHoaDon
     */
    public InsertHoaDon(String idKhach,String tenKhachHang) {
        initComponents();
        txtIDKhachHang.setEditable(false);
        txtTenKhachHang.setEditable(false);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
        loadDanhMucVouCher();
//        loadtaiKhoan();
        this.txtIDKhachHang.setText(idKhach);
        this.txtTenKhachHang.setText(tenKhachHang);
        this.dialogListener = dialogListener;
    }

    private InsertHoaDon() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
  

    @SuppressWarnings("unchecked")
    private void loadDanhMucVouCher() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) CBBVoucher.getModel();
        // xoa du lieu cu
        model.removeAllElements();
        // đỗ dưc liệu mới vào
        List<VoucherEntity> voucherEntitys = voucher.GetAll();
        try {
            for (VoucherEntity p : voucherEntitys) {
                int id = p.getId();
                int phanTramGiam = p.getPhanTramGiam();
                VoucherCBB voucherCBB = new VoucherCBB(id, phanTramGiam);
                model.addElement(voucherCBB);

            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }

//    private void loadKhachHang() {
//        DefaultComboBoxModel model = (DefaultComboBoxModel) CBBKhachHang.getModel();
//        // xoa du lieu cu
//        model.removeAllElements();
//        // đỗ dưc liệu mới vào
//        List<KhachHangEntity> khachHangEntitys = khachHangIMPL.GetAll();
//        try {
//            for (KhachHangEntity p : khachHangEntitys) {
//                int id = p.getId();
//                String hoTen = p.getHoTen();
//                KhachHangCBB khachHangCBB = new KhachHangCBB(id, hoTen);
//                model.addElement(khachHangCBB);
//
//            }
//
//        } catch (Exception e) {
//            e.printStackTrace();
//        }
//
//    }

//    private void loadtaiKhoan() {
//        DefaultComboBoxModel model = (DefaultComboBoxModel) CBBNhanVien.getModel();
//        // xoa du lieu cu
//        model.removeAllElements();
//        // đỗ dưc liệu mới vào
//        List<TaiKhoanEntity> taiKhoanEntitys = taiKhoanIMPL.GetAll();
//        try {
//            for (TaiKhoanEntity p : taiKhoanEntitys) {
//                int id = p.getId();
//                String hoTen = p.getHoTen();
//                TaiKhoanCBB taiKhoanCBB = new TaiKhoanCBB(id, hoTen);
//                model.addElement(taiKhoanCBB);
//
//            }
//
//        } catch (Exception e) {
//            e.printStackTrace();
//        }
//
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnThem = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        CBBVoucher = new javax.swing.JComboBox<>();
        txtIDKhachHang = new javax.swing.JTextField();
        txtTenKhachHang = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Tên Khách Hàng");

        jLabel3.setText("Voucher");

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        CBBVoucher.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtIDKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDKhachHangActionPerformed(evt);
            }
        });

        jLabel4.setText("Id Của Khách :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnThem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClose))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtIDKhachHang)
                            .addComponent(CBBVoucher, 0, 140, Short.MAX_VALUE)
                            .addComponent(txtTenKhachHang))))
                .addContainerGap(179, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtIDKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTenKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CBBVoucher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnClose))
                .addContainerGap(187, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {                                        
        HoaDonEntity hoaDonEntity = new HoaDonEntity();
        KhachHangEntity khachHangEntity = new KhachHangEntity();
        VoucherEntity voucherEntity = new VoucherEntity();
        TaiKhoanEntity taiKhoanEntity = new TaiKhoanEntity();
        int maVouCher;
//        int maKhachHang;
//        int maTaiKhoan;
        ToanCucStatic tt = new ToanCucStatic();
        VoucherCBB voucherCBB = (VoucherCBB) CBBVoucher.getSelectedItem();
        maVouCher = voucherCBB.IdInt();
//        TaiKhoanCBB taiKhoanCBB = (TaiKhoanCBB) CBBNhanVien.getSelectedItem();
//        maTaiKhoan = taiKhoanCBB.IdInt();
        khachHangEntity.setId(Integer.parseInt(txtIDKhachHang.getText()));
        voucherEntity.setId(maVouCher);
        taiKhoanEntity.setId(tt.getIdNhanVien());
        hoaDonEntity.setKhachHangEntity(khachHangEntity);
        hoaDonEntity.setVoucherEntity(voucherEntity);
        hoaDonEntity.setTaiKhoanEntity(taiKhoanEntity);
        hoaDonEntity.setTrangThai(0);
        hoaDonIMPL.Save(hoaDonEntity);
        JOptionPane.showMessageDialog(null, "Thêm hóa đơn thành công.");
        dialogListener.closeDialog();
    }

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void txtIDKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDKhachHangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDKhachHangActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InsertHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InsertHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InsertHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsertHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InsertHoaDon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBBVoucher;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnThem;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtIDKhachHang;
    private javax.swing.JTextField txtTenKhachHang;
    // End of variables declaration//GEN-END:variables

    @Override
    public void closeDialog() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
