/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.da1.view;

import com.mycompany.da1.combobox.KhachHangCBB;
import com.mycompany.da1.combobox.TaiKhoanCBB;
import com.mycompany.da1.combobox.VoucherCBB;
import com.mycompany.da1.entity.*;
import com.mycompany.da1.service.IMPL.HoaDonIMPL;
import com.mycompany.da1.service.IMPL.KhachHangIMPL;
import com.mycompany.da1.service.IMPL.TaiKhoanIMPL;
import com.mycompany.da1.service.IMPL.VoucherServiceIMPL;

import java.util.ArrayList;
import java.util.List;
import javax.swing.*;

/**
 *
 * @author Quang
 */
public class InsertHoaDon extends javax.swing.JFrame {
    VoucherServiceIMPL voucher = new VoucherServiceIMPL();
    KhachHangIMPL khachHangIMPL = new KhachHangIMPL();
     TaiKhoanIMPL taiKhoanIMPL = new TaiKhoanIMPL();
    HoaDonIMPL hoaDonIMPL = new HoaDonIMPL();
    /**
     * Creates new form FormHoaDon
     */
    public InsertHoaDon() {
        initComponents();
        loadDanhMucVouCher();
        loadKhachHang();
        loadtaiKhoan();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        private void loadDanhMucVouCher() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) CBBVoucher.getModel();
        // xoa du lieu cu
        model.removeAllElements();
        // đỗ dưc liệu mới vào
        List<VoucherEntity> voucherEntitys = voucher.GetAll();
        try{
           for (VoucherEntity p:voucherEntitys){
               int id = p.getId();
               int phanTramGiam = p.getPhanTramGiam();
               VoucherCBB voucherCBB = new VoucherCBB(id,phanTramGiam);
               model.addElement(voucherCBB);

           }

        }catch(Exception e){
        e.printStackTrace();
        }

    }
       private void loadKhachHang() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) CBBKhachhang.getModel();
        // xoa du lieu cu
        model.removeAllElements();
        // đỗ dưc liệu mới vào
        List<KhachHangEntity> khachHangEntitys = khachHangIMPL.GetAll();
        try{
           for (KhachHangEntity p:khachHangEntitys){
               int id = p.getId();
               String hoTen = p.getHoTen();
               KhachHangCBB khachHangCBB = new KhachHangCBB(id,hoTen);
               model.addElement(khachHangCBB);

           }

        }catch(Exception e){
            e.printStackTrace();
        }

    }
       private void loadtaiKhoan() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) CBBtaiKhoan.getModel();
        // xoa du lieu cu
        model.removeAllElements();
        // đỗ dưc liệu mới vào
        List<TaiKhoanEntity> taiKhoanEntitys = taiKhoanIMPL.GetAll();
        try{
           for (TaiKhoanEntity p:taiKhoanEntitys){
               int id = p.getId();
               String hoTen = p.getHoTen();
               TaiKhoanCBB taiKhoanCBB = new TaiKhoanCBB(id,hoTen);
               model.addElement(taiKhoanCBB);

           }

        }catch(Exception e){
            e.printStackTrace();
        }

    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        CBBtaiKhoan = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        CBBKhachhang = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        CBBVoucher = new javax.swing.JComboBox<>();
        btnThemHoaDon = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(255, 51, 51));
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setText("Thêm Hóa Đơn Chờ");

        jLabel2.setText("Tên Nhân viên");

        CBBtaiKhoan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setText("Tên Khách hàng");

        CBBKhachhang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CBBKhachhang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBBKhachhangActionPerformed(evt);
            }
        });

        jLabel4.setText("VouCher");

        CBBVoucher.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0" }));
        CBBVoucher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBBVoucherActionPerformed(evt);
            }
        });

        btnThemHoaDon.setText("Thêm");
        btnThemHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemHoaDonActionPerformed(evt);
            }
        });

        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnThemHoaDon)
                                .addGap(77, 77, 77)
                                .addComponent(btnClose))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(CBBKhachhang, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(35, 35, 35)
                                            .addComponent(CBBtaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(CBBVoucher, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(CBBtaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(CBBKhachhang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(CBBVoucher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemHoaDon)
                    .addComponent(btnClose))
                .addContainerGap(103, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemHoaDonActionPerformed(java.awt.event.ActionEvent evt) {
        HoaDonEntity hoaDonEntity = new HoaDonEntity();
        KhachHangEntity khachHangEntity = new KhachHangEntity();
        VoucherEntity voucherEntity = new VoucherEntity();
        TaiKhoanEntity taiKhoanEntity = new TaiKhoanEntity();
        int maVouCher;
        int maKhachHang;
        int maTaiKhoan;
        VoucherCBB voucherCBB = (VoucherCBB) CBBVoucher.getSelectedItem();
        maVouCher = voucherCBB.IdInt();
        KhachHangCBB khachHangCBB = (KhachHangCBB) CBBKhachhang.getSelectedItem();
        maKhachHang=khachHangCBB.IdInt();
        TaiKhoanCBB taiKhoanCBB = (TaiKhoanCBB) CBBtaiKhoan.getSelectedItem();
        maTaiKhoan=taiKhoanCBB.IdInt();
        khachHangEntity.setId(maKhachHang);
        voucherEntity.setId(maVouCher);
        taiKhoanEntity.setId(maTaiKhoan);
        hoaDonEntity.setKhachHangEntity(khachHangEntity);
        hoaDonEntity.setVoucherEntity(voucherEntity);
        hoaDonEntity.setTaiKhoanEntity(taiKhoanEntity);
        hoaDonEntity.setTrangThai(0);
        hoaDonIMPL.Save(hoaDonEntity);
        JOptionPane.showMessageDialog(null, "Thêm hóa đơn thành công.");



       
    }

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
                 this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void CBBVoucherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBBVoucherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBBVoucherActionPerformed

    private void CBBKhachhangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBBKhachhangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBBKhachhangActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InsertHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InsertHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InsertHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsertHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InsertHoaDon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBBKhachhang;
    private javax.swing.JComboBox<String> CBBVoucher;
    private javax.swing.JComboBox<String> CBBtaiKhoan;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnThemHoaDon;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
